services:
  api:
    image: exekaliburr-api
    container_name: exekaliburr-api
    env_file:
      - ./api/.env
    build:
      context: api
      dockerfile: Dockerfile
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    privileged: true
    volumes:
      - ./api/.env:/exekaliburr/api/.env
  front:
    image: exekaliburr-front
    container_name: exekaliburr-front
    env_file:
      - ./front/.env
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "${FRONT_PORT}:3000"
    security_opt:
      - no-new-privileges:true
